name: Mypy

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Mypy
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
              python-version: 3.12
        - name: Install Mypy
          run: pip install mypy
        - name: Mypy
          run: mypy .
